---
project: unknown
MariaDB_version: 5.5.42
MariaDB_role: master
MariaDB_datadir : /data/db-data/hupu.com/{{ project }}
MariaDB_basedir : /usr/local/webserver/DBServer/MariaDB
MariaDB_prompt : ' "(\u@\h)[\d]> " '
MariaDB_default_character_set : utf8
MariaDB_socket : /tmp/mysql.sock
MariaDB_user : mysql
MariaDB_port : 3306
MariaDB_character_set_server: utf8mb4
MariaDB_log_bin_trust_function_creators: 1
MariaDB_query_cache_type : 1
MariaDB_query_cache_limit : 8M
MariaDB_query_cache_min_res_unit : 4k
MariaDB_query_cache_size : 512M
MariaDB_read_buffer_size : 2M
MariaDB_read_rnd_buffer_size : 16M
MariaDB_open_files_limit : 102400
MariaDB_sort_buffer_size : 4M
MariaDB_join_buffer_size : 2M
MariaDB_key_buffer : 1G
MariaDB_key_buffer_size : 1G
MariaDB_table_cache : 2048
MariaDB_max_connections : 2048
MariaDB_back_log : 4000
MariaDB_max_connect_errors : 102400
MariaDB_wait_timeout : 600
MariaDB_interactive_timeout : 3600
MariaDB_tmp_table_size : 512M
MariaDB_slow_query_log : ON
MariaDB_slow_query_log_file : /data0/log-data/mysql-slow.log
MariaDB_long_query_time : 0.5
MariaDB_server_id : "{{ inventory_hostname.split('.')[2] }}{{ inventory_hostname.split('.')[3] }}"
MariaDB_binlog_ignore_db : mysql,test
MariaDB_log_dir : /data0/db-binlog/hupu.com/{{ project }}
MariaDB_log_bin : /data0/db-binlog/hupu.com/{{ project }}/mysql-bin
MariaDB_log_bin_index : /data0/db-binlog/hupu.com/{{ project }}/mysql-bin.index
MariaDB_binlog_format : ROW
MariaDB_binlog_cache_size : 4M
MariaDB_max_binlog_cache_size : 8M
MariaDB_max_binlog_size : 512M
MariaDB_expire_logs_days : 60
MariaDB_bulk_insert_buffer_size : 64M
MariaDB_myisam_sort_buffer_size : 512M
MariaDB_myisam_max_sort_file_size : 1G
MariaDB_myisam_repair_threads : 1
MariaDB_max_heap_table_size : 512M
MariaDB_max_allowed_packet : 1G
MariaDB_thread_concurrency : 8
MariaDB_thread_cache_size : 1024
MariaDB_thread_stack : 192K
MariaDB_innodb_support_xa : OFF
MariaDB_innodb_additional_mem_pool_size : 8M
MariaDB_innodb_buffer_pool_size : "{{ (ansible_memtotal_mb*0.8/1024) | int }}G"
MariaDB_innodb_file_io_threads : 4
MariaDB_innodb_thread_concurrency : 0
MariaDB_innodb_flush_log_at_trx_commit : 2
MariaDB_innodb_log_buffer_size : 8M
MariaDB_innodb_log_files_in_group : 3
MariaDB_innodb_lock_wait_timeout : 60
MariaDB_innodb_file_per_table : 1
MariaDB_innodb_open_files : 1024
MariaDB_innodb_read_io_threads : 16
MariaDB_innodb_write_io_threads : 8
MariaDB_innodb_io_capacity : 2000
MariaDB_innodb_max_dirty_pages_pct : 70
MariaDB_innodb_adaptive_flushing : ON
MariaDB_big_tables : ON
MariaDB_log_error : mysql-error-log.err 
MariaDB_relay_log : mysql-relay-bin
MariaDB_relay_log_index : mysql-relay-bin.index 
MariaDB_replicate_ignore_db : mysql,test
MariaDB_binlog_annotate_row_events : 1
MariaDB_replicate_annotate_row_events : 1
MariaDB_rpl_semi_sync_master_enabled : 1
MariaDB_rpl_semi_sync_slave_enabled : 1
MariaDB_sync_user: canal
MariaDB_sync_password: canalrep
MariaDB_monitor_user: monitor
MariaDB_monitor_password: monitor.db.hupu.com
MariaDB_thread_handling: pool-of-threads
MariaDB_thread_pool_size: 32
MariaDB_thread_pool_max_threads: 2048
MariaDB_thread_pool_idle_timeout: 600
MariaDB_log_slave_updates: 1
MariaDB_pid_file: mysql.pid
